services:
  tinylink_app:
    build:
      args:
        user: Tanvir
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: tinylink
    container_name: tinylink-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./.docker/app/php-fpm.ini:/usr/local/etc/php/conf.d/99-app.ini
    depends_on:
      - tinylink_database
    links:
      - tinylink_database
    networks:
      - tinylink-network
  tinylink_nginx:
    image: nginx:alpine
    container_name: tinylink-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - tinylink-network
    depends_on:
      - tinylink_database
      - tinylink_pma
  tinylink_database:
    image: mariadb
    container_name: tinylink-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - tinylink-network
  tinylink_pma:
    image: phpmyadmin
    container_name: tinylink-pma
    restart: always
    tty: true
    depends_on:
      - tinylink_database
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: tinylink_database
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 2048M
    networks:
      - tinylink-network
networks:
  tinylink-network:
    driver: bridge
